// Generated by https://quicktype.io

export interface ICuestionarioAplicacion {
    atributoResultado:        string;
    descripcion:              string;
    destinatarios:            Destinatario[];
    estatus:                  string;
    fechaCreacion:            string;
    fechaFinalVigencia:       string;
    fechaInicialVigencia:     string;
    fechaModificacion:        string;
    id:                       string;
    idAccount:                string;
    idCicloResultado:         string;
    idMateriaResultado:       string;
    idUsuario:                string;
    materia:                  string;
    mostrarResultadoFinal:    boolean;
    periodoResultado:         string;
    permiteRegresar:          boolean;
    puntosTotales:            number;
    reactivos:                Reactivo[];
    reactivosTotales:         number;
    tiempoMaximoCuestionario: number;
    tipoPresentacion:         string;
    type:                     string;
}

interface Destinatario {
    idUsuario: string;
}

interface Reactivo {
    categoria:              string;
    dificultad:             string;
    estatus:                string;
    fechaCreacion:          string;
    fechaModificacion:      string;
    fijo:                   boolean;
    id:                     string;
    idAccount:              string;
    idUsuario:              string;
    index:                  number;
    isPrivado:              boolean;
    materia:                string;
    mostrarPista:           boolean;
    opciones?:              any[];
    pista:                  string;
    pregunta:               string;
    puntos:                 number;
    tiempoMaximoRespuesta:  number;
    tipoReactivo:           string;
    type:                   Type;
    margenValorNumerico?:   number;
    valorNumericoCorrecto?: number;
    similitudValorTextual?: number;
    valorTextualCorrecto?:  string;
}


enum Type {
    Reactivo = "reactivo",
}
